# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 08:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('first_name', models.CharField(max_length=128, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(blank=True, max_length=128, verbose_name='Apellidos')),
                ('alias', models.CharField(blank=True, max_length=32, verbose_name='Alias')),
                ('organization', models.CharField(blank=True, max_length=64, verbose_name='Organizaci\xf3n')),
                ('borndate', models.DateField(blank=True, verbose_name='Cumplea\xf1os')),
                ('address', models.TextField(blank=True, verbose_name='Direcci\xf3n')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'contacto',
                'verbose_name_plural': 'contactos',
            },
        ),
        migrations.CreateModel(
            name='ContactGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=32, verbose_name='nombre')),
                ('contacts', models.ManyToManyField(related_name='groups', to='base.Contact', verbose_name='contactos')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_groups', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'grupo',
                'verbose_name_plural': 'grupos',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('location', models.PositiveSmallIntegerField(choices=[(0, 'Desconocido'), (1, 'M\xf3vil'), (2, 'Trabajo'), (3, 'Hogar')], default=0, verbose_name='ubicaci\xf3n')),
                ('country_prefix', models.PositiveSmallIntegerField(blank=True, verbose_name='c\xf3digo pais')),
                ('number', models.PositiveIntegerField(verbose_name='n\xfamero')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='base.Contact', verbose_name='contacto')),
            ],
            options={
                'verbose_name': 'tel\xe9fono',
                'verbose_name_plural': 'tel\xe9fonos',
            },
        ),
    ]
