# Generated by Django 5.2.15 on 2026-07-10 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("codenerix", "0001_initial"),
        ("codenerix", "0002_auto_20160808_0843"),
        ("codenerix", "0003_auto_20160817_1235"),
        ("codenerix", "0004_auto_20160824_0757"),
        ("codenerix", "0005_auto_20160824_1332"),
        ("codenerix", "0006_auto_20160825_0838"),
        ("codenerix", "0007_corporateimage"),
        ("codenerix", "0008_auto_20170119_1526"),
        ("codenerix", "0009_delete_corporateimage"),
        ("codenerix", "0010_corporateimage"),
        ("codenerix", "0011_delete_corporateimage"),
        ("codenerix", "0012_auto_20170405_0815"),
        ("codenerix", "0013_auto_20170410_1429"),
        ("codenerix", "0014_auto_20170418_1011"),
        ("codenerix", "0015_auto_20170418_1515"),
        ("codenerix", "0016_auto_20170419_1533"),
        ("codenerix", "0017_auto_20170428_0850"),
        ("codenerix", "0018_log_snapshot_txt"),
        ("codenerix", "0019_auto_20170725_1822"),
        ("codenerix", "0020_remotelog"),
        ("codenerix", "0021_auto_20171218_1039"),
        ("codenerix", "0022_alter_log_options"),
        ("codenerix", "0023_alter_log_content_type_alter_log_user_and_more"),
        ("codenerix", "0024_alter_remotelog_options"),
    ]

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_time",
                    models.DateTimeField(auto_now=True, verbose_name="Date"),
                ),
                (
                    "object_id",
                    models.TextField(blank=True, null=True, verbose_name="Object id"),
                ),
                (
                    "object_repr",
                    models.CharField(max_length=200, verbose_name="Object repr"),
                ),
                (
                    "action_flag",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Add"), (2, "Change"), (3, "Delete")],
                        verbose_name="Action",
                    ),
                ),
                ("change_json", models.TextField(blank=True, verbose_name="Json")),
                ("change_txt", models.TextField(blank=True, verbose_name="Txt")),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="log",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "snapshot_txt",
                    models.TextField(blank=True, verbose_name="Snapshot Txt"),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Username"
                    ),
                ),
            ],
            options={
                "permissions": [
                    ("list_log", "Can list log"),
                    ("detail_log", "Can view log"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RemoteLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="Updated"),
                ),
                ("data", models.TextField(verbose_name="Data")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="remotelog",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Username"
                    ),
                ),
            ],
            options={
                "abstract": False,
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                ),
            },
        ),
    ]
