# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-10 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codenerix', '0012_auto_20170405_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action_flag',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Add'), (2, 'Change'), (3, 'Delete')], verbose_name='Action'),
        ),
    ]
