# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 10:11
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("codenerix", "0013_auto_20170410_1429"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="action_flag",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "A\xf1adir"), (2, "Modificar"), (3, "Eliminar")],
                verbose_name="Acci\xf3n",
            ),
        ),
    ]
