# Generated by Django 1.10.6 on 2017-04-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("codenerix", "0014_auto_20170418_1011"),
    ]

    operations = [
        migrations.AlterField(
            model_name="log",
            name="action_flag",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Add"), (2, "Change"), (3, "Delete")],
                verbose_name="Action",
            ),
        ),
    ]
