# Generated by Django 5.2.12 on 2026-03-27 13:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("codenerix", "0023_alter_log_content_type_alter_log_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="remotelog",
            options={
                "default_permissions": (
                    "add",
                    "change",
                    "delete",
                    "view",
                    "list",
                    "detail",
                ),
            },
        ),
    ]
